# Ficha del mod. La lee el panel MODS.
nombre = Digivice
autor  = Jeanheck
version = 1.0
descripcion = Digivice is a real-time, 3DS-style companion screen for Digimon World 2003 on Duckstation that automatically tracks your party's EXP, quest progress, evolution trees, map details, and hidden events right beside your game.
avatar  = autor.jpg
enlace = https://github.com/jeanheck
categoria = ui
